server:
  port: 3004
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/keyur-github/microservice-configuration
          clone-on-start: true
